spring:
    datasource:
      url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
      username: root
      password: 123456
      #schema: database/import.sql
#      sql-script-encoding: utf-8
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      initialSize : 5
      minIdle : 5
      maxActive : 20
      maxWait : 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      useGlobalDataSourceStat: true
    jpa:
      database: mysql
      show-sql: true
      hibernate:
        ddl-auto: update
        naming:
          strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect

    thymeleaf:
       cache: false
       mode: LEGACYHTML5

    redis:
      database: 0
      host: localhost
      port: 6379
      password:
      pool:
        max-active: 8
        min-idle: 0
        max-wait: -1
      timeout: 0
    data:
      elasticsearch:
#        host: 127.0.0.1
#        port: 9300
        cluster-name: elasticsearch
        cluster-nodes: 127.0.0.1:9300
#        properties:
#            path:
#              logs: ./elasticsearch/log #elasticsearch日志存储目录
#              data: ./elasticsearch/data #elasticsearch数据存储目录
        repositories:
          enabled: true
logging:
  config:classpath:logback.xml

